#!/usr/bin/env bash
# scripts/quick-reference.sh
# Referencia rápida de comandos

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 TableroQA - Referencia Rápida de Comandos"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🚀 INSTALACIÓN Y SETUP"
echo "────────────────────────────────────────────────────────"
echo "npm install                          # Instalar dependencias"
echo "npm install sqlite3                  # Instalar SQLite"
echo "node scripts/load-xlsx-to-sqlite.js  # Cargar datos XLSX"
echo ""

echo "▶️  DESARROLLO"
echo "────────────────────────────────────────────────────────"
echo "npm run dev                  # Servidor de desarrollo"
echo "npm run build                # Compilación producción"
echo "npm run lint                 # Lint del código"
echo ""

echo "🔍 VERIFICACIÓN Y DEBUG"
echo "────────────────────────────────────────────────────────"
echo "node lib/db-status.js        # Estado de BD"
echo "ls -la data/tableroqua.db    # Verificar archivo BD"
echo ""

echo "📡 APIs DISPONIBLES (http://localhost:3000)"
echo "────────────────────────────────────────────────────────"
echo "GET /api/qa-data-v2                        # Datos QA"
echo "GET /api/qa-data-v2?type=summary           # Resumen ejecutivo"
echo "GET /api/qa-data-v2?type=bugs-by-status    # Bugs por estado"
echo "GET /api/qa-data-v2?type=bugs-by-module    # Bugs por módulo"
echo "GET /api/qa-data-v2?type=bugs-by-developer # Bugs por dev"
echo "GET /api/search-bugs?status=X&module=Y     # Búsqueda"
echo "GET /api/quality-report                    # Reporte calidad"
echo ""

echo "🛠️  DESARROLLO (COMANDOS ÚTILES)"
echo "────────────────────────────────────────────────────────"
echo "# Recargar datos desde XLSX"
echo "node scripts/load-xlsx-to-sqlite.js"
echo ""
echo "# Ver estado de BD"
echo "node lib/db-status.js"
echo ""
echo "# Compilar y verificar"
echo "npm run build"
echo ""

echo "📚 DOCUMENTACIÓN"
echo "────────────────────────────────────────────────────────"
echo "IMPLEMENTACION_COMPLETA.md       # Resumen de cambios"
echo "ARQUITECTURA_SIMPLIFICADA.md     # Arquitectura técnica"
echo "SQLITE_SETUP_GUIDE.md            # Guía de instalación"
echo ""

echo "💾 ARCHIVOS IMPORTANTES"
echo "────────────────────────────────────────────────────────"
echo "data/tableroqua.db               # BD SQLite (110 KB)"
echo "data/load-info.json              # Info última carga"
echo "lib/sqlite-db.js                 # Gestor BD"
echo "lib/sqlite-queries.js            # Consultas SQL"
echo "scripts/load-xlsx-to-sqlite.js   # Script carga"
echo ""

echo "📊 ESTADÍSTICAS ACTUALES"
echo "────────────────────────────────────────────────────────"
echo "Bugs: 138 | Sprints: 7 | Versiones: 7"
echo "Desarrolladores: 17 | Módulos: 13"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
